import{S as $,i as l}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const v="https://pixabay.com/api/",H="47417091-7b1b728bfc28f8d5b77701890",h=async(e,r=1,s=15)=>{const n=`${v}?key=${H}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`;try{const t=await fetch(n);if(!t.ok)throw new Error("Failed to fetch images");return await t.json()}catch(t){throw console.error(t),t}},p=e=>e.map(({webformatURL:r,largeImageURL:s,tags:n,likes:t,views:o,comments:d,downloads:L})=>`
      <a href="${s}" class="gallery-item" title="${n}">
          <img src="${r}" alt="${n}" loading="lazy">
          <div class="info">
              <p><b>Likes</b> ${t}</p>
              <p><b>Views</b> ${o}</p>
              <p><b>Comments</b> ${d}</p>
              <p><b>Downloads</b> ${L}</p>
          </div>
      </a>
  `).join(""),S=e=>{e.innerHTML=""},c=(e,r)=>{e.style.display=r?"block":"none"},b=document.querySelector("#search-form"),y=document.querySelector(".gallery"),a=document.querySelector(".loader"),u=document.querySelector("#load-more");let g=new $(".gallery a"),i=1,m="",f=0;b.addEventListener("submit",async e=>{e.preventDefault();const r=b.elements.searchQuery.value.trim();if(!r){l.error({title:"Помилка",message:"Будь ласка, введіть пошуковий запит!"});return}m=r,i=1,f=0,S(y),c(a,!0),u.style.display="none";try{const s=await h(m,i);if(f=s.totalHits,s.hits.length===0){l.warning({title:"Немає результатів",message:"Не знайдено зображень. Спробуйте інше ключове слово!"});return}const n=p(s.hits);y.insertAdjacentHTML("beforeend",n),g.refresh(),s.hits.length===15&&f>15&&(u.style.display="block")}catch{l.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте ще раз!"})}finally{c(a,!1)}});u.addEventListener("click",async()=>{i+=1,c(a,!0);try{const e=await h(m,i),r=p(e.hits);y.insertAdjacentHTML("beforeend",r),g.refresh(),w(),(e.hits.length<15||(i-1)*15+e.hits.length>=f)&&(u.style.display="none",l.info({title:"Кінець результатів",message:"На жаль, ви досягли кінця результатів пошуку."}))}catch{l.error({title:"Помилка",message:"Не вдалося завантажити більше зображень!"})}finally{c(a,!1)}});const w=()=>{const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}};window.addEventListener("scroll",async()=>{if(window.innerHeight+window.scrollY>=document.body.offsetHeight-500&&!a.style.display){i+=1,c(a,!0);try{const e=await h(m,i),r=p(e.hits);y.insertAdjacentHTML("beforeend",r),g.refresh(),w(),(e.hits.length<15||(i-1)*15+e.hits.length>=f)&&(u.style.display="none",l.info({title:"Кінець результатів",message:"На жаль, ви досягли кінця результатів пошуку."}))}catch{l.error({title:"Помилка",message:"Не вдалося завантажити більше зображень!"})}finally{c(a,!1)}}});
//# sourceMappingURL=index.js.map
